name: MetaCrow
favicon: null
layout_spectrum: 0.17369
typography_spectrum: 0.29897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-30796738-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#093b2e'
    - '#feecca'
    - '#007b5b'
    - '#958285'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
