name: MetaCrow
favicon: null
layout_spectrum: 0.75078
typography_spectrum: 0.75154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-30796738-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6d6a69'
    - '#0000ff'
    - '#ff0000'
    - '#c8c8c8'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
