name: MetaCrow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-30796738-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.25347509956918657
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
